### ISSUE TITLE
Deployment instructions

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#161]

**Comment by DavidMStraub** [comment]
Nice, building the docker image with Github actions worked (see here: https://hub.docker.com/repository/docker/dmstraub/gramps-webapi). I will write some deployment instructions based on this tomorrow.

**Comment by vnl** [comment]
I somehow get a python error trying your docker image as well as the direct install. 
docker run issue:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/gramps_webapi/wsgi.py", line 23, in <module>
    app = create_app()
  File "/usr/local/lib/python3.7/dist-packages/gramps_webapi/app.py", line 54, in create_app
    app.config["DB_MANAGER"] = WebDbManager(name=app.config["TREE"])
KeyError: 'TREE'
[2021-01-02 09:41:14 +0000] [11] [INFO] Worker exiting (pid: 11)
[2021-01-02 09:41:15 +0000] [12] [ERROR] Exception in worker process
Traceback (most recent call last):...
....
File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>`

Not able to run the pytest:
`▶ pytest
=========================================================== test session starts ============================================================
platform darwin -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /Users/viv/Downloads/Dev/GrampsWeb/gramps-webapi
collected 0 items / 35 errors

================================================================== ERRORS ==================================================================
____________________________________________________ ERROR collecting tests/test_cli.py ____________________________________________________
ImportError while importing test module '/Users/viv/Downloads/Dev/GrampsWeb/gramps-webapi/tests/test_cli.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/__init__.py:34: in <module>
    from gramps.cli.clidbman import CLIDbManager
E   ModuleNotFoundError: No module named 'gramps'`

Is this because my python version does not match? I installed Gramps. I, unfortunately, have a Mac and so I assumed the Gramps installation would get the python-gramps libraries required. 

Any help here is appreciated.

**Comment by DavidMStraub** [comment]
`KeyError: 'TREE'` means you haven't configured which family tree to use.

Please wait for the instructions, then let's debug if that doesn't work.

**Comment by DavidMStraub** [comment]
First step: [Config documentation in the wiki](https://github.com/gramps-project/gramps-webapi/wiki/Configuration).

**Comment by DavidMStraub** [comment]
I added docker deployment instructions in the wiki: https://github.com/gramps-project/gramps-webapi/wiki/Deployment

Please let me know if this is clear (and if it works).
