### ISSUE TITLE
Error - No thumbnailer found for MIME type video/mp4 

### ISSUE THREAD

**Issue by brucejackson** [gramps-project/gramps-webapi#263]
I started digitizing 8mm films and adding them as media objects in Gramps.  Using GrampsWeb when I browse the media object page (`/media/grampsID`), I receive the error message below in Docker.  In Gramps Desktop the file plays using the default app for that `mime/type` on the computer.  

It would be a nice enhancement to use the HTML `video` and `audio` tags to allow these files to be played on the Media Object page in GrampsWeb.   

It looks to me that the error below is complaining about the lack of a method to create a thumbnail for video mime-types.   GrampsWeb may need to have a generic thumbnail for audio files (https://commons.wikimedia.org/wiki/Category:Sound_file_icons) and video icons (https://commons.wikimedia.org/wiki/Category:Video_icons).  Presumably, with generic icons, it would allow the media objects listed in the Gallery Tab on People, Places, Events, etc.

`[2021-12-27 14:57:52 +0000] [14] [ERROR] Error handling request /api/media/ee9a340f6b8527ddf332bc9edd2/thumbnail/3000?jwt=tokenvalue&square=false
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/auth.py", line 45, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/webargs/core.py", line 450, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask_caching/__init__.py", line 475, in decorated_function
    rv = f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/__init__.py", line 250, in get_thumbnail
    return handler.send_thumbnail(size=size, square=args["square"])
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/file.py", line 127, in send_thumbnail
    thumb = ThumbnailHandler(self.path_abs, self.mime)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/image.py", line 101, in __init__
    raise ValueError(
ValueError: No thumbnailer found for MIME type video/mp4.`

Thanks,
Bruce.

**Comment by brucejackson** [comment]
It looks like a less generic thumbnail could be created for videos using ffmpeg.  

`ffmpeg  -i movie.mp4 -i play.png -filter_complex "[0:v][1:v]overlay=main_w/2-overlay_w/2:main_h/2-overlay_h/2" -vframes 1 thumbnail.png`

I tried it on a video and got this thumbnail.  
![output](https://user-images.githubusercontent.com/1219029/147486392-83ff12ce-a72d-4752-a1ba-c575f817a73c.png)

Source: https://stackoverflow.com/questions/25498218/ffmpeg-adding-play-image-to-thumbnail-output/25499933#25499933

**Comment by DavidMStraub** [comment]
Thanks! Good point.

**Comment by DavidMStraub** [comment]
Can you please check if the implementation in #264 works for you? (Gramps Web should show the thumbnails, but not the videos yet). I have only tested it with a single file.

**Comment by brucejackson** [comment]
Thanks.  I tried to pull an updated image (latest-devel) so I can test but
docker tells me I have the most current image.  Does it take a while before
it is available?

**Comment by brucejackson** [comment]
I've just realized you haven't merged the changes from your branch into the
master - hence no docker image.  I've looked at the commits you made and I
think it looks good.

As an aside, I gave my mother access to our Family Tree via GrampsWeb and
she is really impressed by your work and the presentation.

**Comment by DavidMStraub** [comment]
Finally added the UI for audio & video files to Gramps Web as well.

**Comment by brucejackson** [comment]
Thanks for flagging the update for me.  Looks great!
