### ISSUE TITLE
GrampsWeb container constantly restarting after updating container image

### ISSUE THREAD

**Issue by brucejackson** [gramps-project/gramps-webapi#302]
Good Morning,

I've just updated my GrampsWeb to the new latest-devel image of GrampsWeb that was published yesterday (July 19).  I wanted to test the new UI for video and audio.   After recreating my container, the GrampsWeb container is constantly restarting with the error below.  

Thanks

```

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> c89728e71264, empty message
INFO  [alembic.runtime.migration] Running upgrade c89728e71264 -> e5e738d09fa7, Added configuration table
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table configuration already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/alembic/__main__.py", line 4, in <module>
    main(prog="alembic")
  File "/usr/local/lib/python3.9/dist-packages/alembic/config.py", line 590, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.9/dist-packages/alembic/config.py", line 584, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.9/dist-packages/alembic/config.py", line 561, in run_cmd
    fn(
  File "/usr/local/lib/python3.9/dist-packages/alembic/command.py", line 322, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.9/dist-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.9/dist-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.9/dist-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "alembic_users/env.py", line 93, in <module>
    run_migrations_online()
  File "alembic_users/env.py", line 87, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.9/dist-packages/alembic/runtime/environment.py", line 853, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.9/dist-packages/alembic/runtime/migration.py", line 623, in run_migrations
    step.migration_fn(**kw)
  File "/app/src/alembic_users/versions/e5e738d09fa7_added_configuration_table.py", line 21, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/usr/local/lib/python3.9/dist-packages/alembic/operations/ops.py", line 1254, in create_table
    return operations.invoke(op)
  File "/usr/local/lib/python3.9/dist-packages/alembic/operations/base.py", line 399, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.9/dist-packages/alembic/operations/toimpl.py", line 114, in create_table
    operations.impl.create_table(table)
  File "/usr/local/lib/python3.9/dist-packages/alembic/ddl/impl.py", line 354, in create_table
    self._exec(schema.CreateTable(table))
  File "/usr/local/lib/python3.9/dist-packages/alembic/ddl/impl.py", line 195, in _exec
    return conn.execute(construct, multiparams)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1306, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1398, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table configuration already exists
[SQL: 
CREATE TABLE configuration (
        id INTEGER NOT NULL, 
        "key" VARCHAR NOT NULL, 
        value VARCHAR, 
        PRIMARY KEY (id), 
        UNIQUE ("key")
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by DavidMStraub** [comment]
Oh OK, I will fix it.

Just to understand when that happens: do you remember if you pulled latest-devel in the last 11 days as well, i.e. after https://github.com/gramps-project/gramps-webapi/commit/54619f8ae348687fb1dc338e72c6b7931dba7d34?

**Comment by DavidMStraub** [comment]
Can you try now?

**Comment by brucejackson** [comment]
Thanks for the fast fix.  It's working again!
