### ISSUE TITLE
Database backend 'bsddb' of tree 'postgres' not supported.

### ISSUE THREAD

**Issue by MegaThorx** [gramps-project/gramps-webapi#369]
I'm unable to run grampsweb with postgres. With the configuration in my gist I receive the following error upon starting it with `docker compose up`.

Setup: https://gist.github.com/MegaThorx/7bbeb75598efb60337a2c29f11570f36

```
gramps-grampsweb-1        | Traceback (most recent call last):
gramps-grampsweb-1        |   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
gramps-grampsweb-1        |     return _run_code(code, main_globals, None,
gramps-grampsweb-1        |   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
gramps-grampsweb-1        |     exec(code, run_globals)
gramps-grampsweb-1        |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 195, in <module>
gramps-grampsweb-1        |     cli(
gramps-grampsweb-1        |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
gramps-grampsweb-1        |     return self.main(*args, **kwargs)
gramps-grampsweb-1        |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
gramps-grampsweb-1        |     rv = self.invoke(ctx)
gramps-grampsweb-1        |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1654, in invoke
gramps-grampsweb-1        |     super().invoke(ctx)
gramps-grampsweb-1        |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
gramps-grampsweb-1        |     return ctx.invoke(self.callback, **ctx.params)
gramps-grampsweb-1        |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
gramps-grampsweb-1        |     return __callback(*args, **kwargs)
gramps-grampsweb-1        |   File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 26, in new_func
gramps-grampsweb-1        |     return f(get_current_context(), *args, **kwargs)
gramps-grampsweb-1        |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 54, in cli
gramps-grampsweb-1        |     ctx.obj = {"app": create_app()}
gramps-grampsweb-1        |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/app.py", line 111, in create_app
gramps-grampsweb-1        |     WebDbManager(name=app.config["TREE"], create_if_missing=True)
gramps-grampsweb-1        |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbmanager.py", line 69, in __init__
gramps-grampsweb-1        |     self._check_backend()
gramps-grampsweb-1        |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbmanager.py", line 137, in _check_backend
gramps-grampsweb-1        |     raise ValueError(
gramps-grampsweb-1        | ValueError: Database backend 'bsddb' of tree 'postgres' not supported.
```

**Comment by DavidMStraub** [comment]
Hi, did you follow these instructions? https://gramps-project.github.io/web/Postgres/

**Comment by MegaThorx** [comment]
Well that was quick :)

I'm using the "Dockerfile" as mentioned in the documentation there. I've skipped the importing step and continued with the configuration part.

Do I need to do something special to enable the postgres plugin? I already checked the container and it contains the plugin.

Do I need the base structure from the import in the database? But at the moment there is not even a connection to the postgres yet.

**Comment by DavidMStraub** [comment]
You need to set up the Postgres database and the Gramps database before starting Web API. The Postgres plugin will work if there is a Gramps database at `/root/.gramps/grampsdb` which has the string `postgresql` in the file `database.txt` and the credentials in `settings.ini`.

**Comment by MegaThorx** [comment]
Perfect ;)

I created the database with gramps desktop and then copied the project into the db folder of grampsweb.

While creating the family tree I've encountered the following error which I resolved with:
`CREATE COLLATION IF NOT EXISTS "de" (locale = "de_AT.utf8")`
![](https://ass.merx.dev/robust-furry-nag/direct)
