### ISSUE TITLE
Task queue crashing on media import

### ISSUE THREAD

**Issue by derpferd** [gramps-project/gramps-webapi#397]
Versions:
```
Gramps 5.1.5
Gramps Web API 1.1.7
Gramps.js 0.22.2
locale: en
multi-tree: false
task queue: true
```

Error Stack Trace:
```
[2023-07-24 00:14:15,534: ERROR/ForkPoolWorker-4] Task gramps_webapi.api.tasks.import_media_archive[f6af07b4-cef7-4aa0-815e-8a3acbd92bdf] raised unexpected: RuntimeError('You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/util/celery.py", line 20, in __call__                                                                                         
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/tasks.py", line 212, in import_media_archive                                                                              
    result = run_import_media_archive(
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/resources/util.py", line 1283, in run_import_media_archive                                                                
    check_quota_media(to_add=upload_size, tree=tree)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/media.py", line 343, in check_quota_media                                                                                 
    update_usage_media()
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/media.py", line 329, in update_usage_media                                                                                
    tree = get_tree_from_jwt()
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/util.py", line 128, in get_tree_from_jwt                                                                                  
    claims = get_jwt()
  File "/usr/local/lib/python3.9/dist-packages/flask_jwt_extended/utils.py", line 29, in get_jwt                                                                                           
    raise RuntimeError(
RuntimeError: You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method
```

Steps to reproduce:

1. Setup instance via [docker-compose](https://raw.githubusercontent.com/gramps-project/web/main/examples/docker-compose-base/docker-compose.yml).
2. Follow steps for "Import Media Files" and upload zip file.

**Comment by DavidMStraub** [comment]
Thanks, I think it's the same issue mentioned here on the forum: https://gramps.discourse.group/t/error-uploading-media-zip-you-must-call-jwt-required-or-verify-jwt-in-request-before-using-this-method/3815/4

Can you please check whether your database schema is up to date?

```
python3 -m gramps_webapi --config path/to/config.cfg user migrate
```

**Comment by derpferd** [comment]
I get the following error when running that command:

```
root@ff2d5f0a5abb:/app# python3 -m gramps_webapi --config /app/config/config.cfg user migrate
  FAILED: No config file 'alembic.ini' found, or file has no '[alembic]' section
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 199, in <module>
    cli(
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 119, in migrate_db
    subprocess.run(cmd, env=env, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'alembic', 'upgrade', 'head']' returned non-zero exit status 255.
```

**Comment by derpferd** [comment]
Got the migrate script to work under a different directory:

```
root@ff2d5f0a5abb:/app/src# /usr/bin/python3 -m alembic upgrade head
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
```

**Comment by derpferd** [comment]
Still getting 

```
[2023-07-24 17:02:22,523: ERROR/ForkPoolWorker-4] Task gramps_webapi.api.tasks.import_media_archive[3d16945c-2d10-45ca-85c1-74689432845c] raised unexpected: RuntimeError('You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/util/celery.py", line 20, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/tasks.py", line 212, in import_media_archive
    result = run_import_media_archive(
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/resources/util.py", line 1283, in run_import_media_archive
    check_quota_media(to_add=upload_size, tree=tree)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/media.py", line 344, in check_quota_media
    update_usage_media(tree)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/media.py", line 331, in update_usage_media
    db_handle = get_db_handle(tree=tree)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/util.py", line 167, in get_db_handle
    view_private = has_permissions({PERM_VIEW_PRIVATE})
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/auth.py", line 79, in has_permissions
    claims = get_jwt()
  File "/usr/local/lib/python3.9/dist-packages/flask_jwt_extended/utils.py", line 29, in get_jwt
    raise RuntimeError(
RuntimeError: You must call `@jwt_required()` or `verify_jwt_in_request()` before using this method
```

**Comment by derpferd** [comment]
Restarted Docker container after DB migration and it appears to be working now.

**Comment by DavidMStraub** [comment]
Ok thanks for checking.

**Comment by derpferd** [comment]
Got it working after making these changes: https://github.com/gramps-project/gramps-webapi/compare/b17e0eb54bcee9c4b4592ecec02a19e0c6f7bc8e..derpferd:gramps-webapi:d2c1be5e75ea468cd7a387456996b3f95e5ba633 (ignore the Dockerfile change, that was just a docker build time optimization).

I see your PR #403 . However this was not good enough for me checkout my diff for details (`check_quota_media` was causing issues however my diff doesn't fix this it just disables it.)

**Comment by DavidMStraub** [comment]
Hi,

thanks, but in your diff you simply commented out the call to the function that caused the bug, which removes the error but also removes the check of the media quota, so it's not a solution.

Did you still get the bug with my PR's code? If so, can you please share the traceback?

Thanks.

**Comment by DavidMStraub** [comment]
Sorry, but for me it works, so I will merge it and release a new version. Please let me know if you still have issues then.
