### ISSUE TITLE
500 when getting citations

### ISSUE THREAD

**Issue by alcaprar** [gramps-project/gramps-webapi#402]
Failing calls:
- `GET /api/citations/?locale=it&profile=all&extend=all&rules={"function":"or","rules":[{"name":"HasIdOf","values":["C0051"]},{"name":"HasIdOf","values":["C0052"]},{"name":"HasIdOf","values":["C0053"]}]}`
- `GET /api/citations/?extend=source_handle&keys=gramps_id,extended,change&page=1&pagesize=20&sort=-change`

Logs from docker:
```
ERROR:root:Error parsing list of recent DBs from file /root/.gramps/recent-files-gramps.xml: no element found: line 1, column 0.
This might indicate a damage to your files.
If you're sure there is no problem with other files, delete it, and restart Gramps.
[2023-07-31 13:39:08 +0000] [19] [ERROR] Error handling request /api/citations/?locale=it&profile=all&extend=all&rules=%7B%22function%22%3A%22or%22%2C%22rules%22%3A%5B%7B%22name%22%3A%22HasIdOf%22%2C%22values%22%3A%5B%22C0051%22%5D%7D%2C%7B%22name%22%3A%22HasIdOf%22%2C%22values%22%3A%5B%22C0052%22%5D%7D%2C%7B%22name%22%3A%22HasIdOf%22%2C%22values%22%3A%5B%22C0053%22%5D%7D%5D%7D
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/auth.py", line 45, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 188, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/webargs/core.py", line 594, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/resources/base.py", line 404, in get
    [
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/resources/base.py", line 405, in <listcomp>
    self.full_object(query_method(handle), args, locale=locale)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/resources/base.py", line 79, in full_object
    obj = self.object_extend(obj, args, locale=locale)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/resources/citations.py", line 51, in object_extend
    obj.profile = get_citation_profile_for_object(
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/resources/util.py", line 560, in get_citation_profile_for_object
    source = db_handle.get_source_from_handle(citation.source_handle)
  File "/usr/lib/python3/dist-packages/gramps/gen/db/generic.py", line 1291, in get_source_from_handle
    return self._get_from_handle(SOURCE_KEY, Source, handle)
  File "/usr/lib/python3/dist-packages/gramps/gen/db/generic.py", line 1263, in _get_from_handle
    raise HandleError('Handle is None')
gramps.gen.errors.HandleError: Handle is None
```

**Comment by DavidMStraub** [comment]
Hi, please copy & paste the version info from Settings -> System Info and also provide more details about your setup. How did you import the data? XML, database, sync?

**Comment by alcaprar** [comment]
Sorry If I came back this late.
I am using docker and this is the version that's running: `grampsweb:v0.19.1`.
I imported the database.

**Comment by alcaprar** [comment]
I just double-checked and I think the first 3 lines of the previous log snippet are not related to the citations problem:
```
ERROR:root:Error parsing list of recent DBs from file /root/.gramps/recent-files-gramps.xml: no element found: line 1, column 0.
This might indicate a damage to your files.
If you're sure there is no problem with other files, delete it, and restart Gramps.
```

**Comment by DavidMStraub** [comment]
Hi, the latter is a warning issued by Gramps core. You can ignore it.

Concerning the original issue, I suspect what happened is that an object got corrupted due to a missing form validation, could it be?
https://github.com/gramps-project/Gramps.js/issues/282

**Comment by alcaprar** [comment]
Yea, the object is corrupted indeed. I tried to export the DB and view it from Gramps desktop and it's corrupted.
What's the best way to delete this?

**Comment by DavidMStraub** [comment]
If you have a backup (Gramps desktop creates one every time you close it), you could try the check & repair tool or exporting to XML. A low level solution would be to delete the object directly in the SQLite database using sqlitebrowser. Please let me know which avenau worked or didn't, in case other users have this problem as well.

**Comment by alcaprar** [comment]
I ended up using `sqlite3` CLI and deleted the broken citation directly from the db.
