### ISSUE TITLE
Database backend error

### ISSUE THREAD

**Issue by Gregoor** [gramps-project/gramps-webapi#463]
Hi again,

I tried following the guide over at https://www.grampsweb.org/Deployment/ but ran into the following error:
```
code-grampsweb-1  | Traceback (most recent call last):
code-grampsweb-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
code-grampsweb-1  |   File "<frozen runpy>", line 88, in _run_code
code-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/__main__.py", line 202, in <module>
code-grampsweb-1  |     cli(
code-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1157, in __call__
code-grampsweb-1  |     return self.main(*args, **kwargs)
code-grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
code-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1078, in main
code-grampsweb-1  |     rv = self.invoke(ctx)
code-grampsweb-1  |          ^^^^^^^^^^^^^^^^
code-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1685, in invoke
code-grampsweb-1  |     super().invoke(ctx)
code-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1434, in invoke
code-grampsweb-1  |     return ctx.invoke(self.callback, **ctx.params)
code-grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
code-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 783, in invoke
code-grampsweb-1  |     return __callback(*args, **kwargs)
code-grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
code-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/click/decorators.py", line 33, in new_func
code-grampsweb-1  |     return f(get_current_context(), *args, **kwargs)
code-grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
code-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/__main__.py", line 53, in cli
code-grampsweb-1  |     ctx.obj = {"app": create_app()}
code-grampsweb-1  |                       ^^^^^^^^^^^^
code-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/app.py", line 108, in create_app
code-grampsweb-1  |     WebDbManager(
code-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/dbmanager.py", line 72, in __init__
code-grampsweb-1  |     self._check_backend()
code-grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/dbmanager.py", line 145, in _check_backend
code-grampsweb-1  |     raise ValueError(
code-grampsweb-1  | ValueError: Database backend 'bsddb' of tree 'Gramps Web' not supported.
```

That is on my local machine, over on my test host I have not gotten it to start yet, it seems to run out of resources. But anyway, that's beside the point here.

Since I'm new to this project I thought I'd stop digging too much and just ask, in the hopes someone more experience has a quick idea for me :)

**Comment by Gregoor** [comment]
Woops, thanks for the issue transfer!

I'm trying it without any prior Gramps db, I assumed it would create one during setup, am I mistaken in that assumption?

**Comment by Gregoor** [comment]
Ah, I was not specifying a config yet, and I guess that defaulted to bsddb? After using https://www.grampsweb.org/Deployment/#configuration-file-vs-environment-variables to specify a config which contained a `TREE` value the error went away.

I'm getting 403 on the web interface now but I'll continue digging myself from here. Thanks for the swift help!
